config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	get '/logout', to: 'sessions#destroy'
	get '/register', to: 'brankdays#new'
	post '/register', to: 'brankdays#create'
	get '/makegroup', to: 'groups#new'
	post '/makegroup', to: 'groups#create'
	get '/joingroup', to: 'belongs#new'
	post '/joingroup', to: 'belongs#create'
	get '/detail', to: 'groups#detail'
	resources :users
	resources :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belong.rb
class Belong < ApplicationRecord
end

app/models/brankdays.rb
class Brankdays < ApplicationRecord

end

app/models/group.rb
class Group < ApplicationRecord
	validates :name, presence: true, length: { maximum: 50},
									 uniqueness: { case_sensitive: false }

  has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord

	validates :name, presence: true, length: { maximum: 50},
									 uniqueness: { case_sensitive: false }

  has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/belongs_controller.rb
class BelongsController < ApplicationController
	include SessionsHelper

  def new
  end

	def create
		group = Group.find_by(name: params[:belong][:name]);
		if group && group.authenticate(params[:belong][:password])
			@belong = Belong.new(user_id: current_user.id, group_id: group.id)
			@belong.save
			redirect_to root_path
		else
			flash.now[:danger] = "Invalid name/password combination"
			render 'new'
		end
	end

  def show
  end
end

app/controllers/brankdays_controller.rb
class BrankdaysController < ApplicationController

	include SessionsHelper

  def show
  end

  def new
  end

	def create
		for week in 1..7 do
			for time in 1..5 do
				if params[:register][:"#{week}_#{time}"] == "1"
					query = "SELECT COUNT(*) AS count_check FROM brankdays WHERE day_id = #{week} 
										AND time_id = #{time} AND user_id = #{current_user.id}"
					if Brankdays.find_by_sql(query).first.count_check == 0
						@brankdays = Brankdays.new(day_id: week, time_id: time, user_id: current_user.id)
						@brankdays.save
					end
				else
					query = "DELETE FROM brankdays WHERE day_id = #{week} 
										AND time_id = #{time} AND user_id = #{current_user.id}"
					ActiveRecord::Base.connection.execute(query)
				end
			end
		end
		redirect_to current_user
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	include SessionsHelper

  def new
		@group = Group.new
  end

	def create
		@group = Group.new(group_params)
		if @group.save
			@belong = Belong.new(user_id: current_user.id, group_id: @group.id)
			@belong.save
			redirect_to root_path
		else
			render 'new'
		end
		
	end

  def show
		@group = Group.find(params[:id])
		query = "SELECT user_id FROM belongs WHERE group_id = #{@group.id}"
		user_belongs = Belong.find_by_sql(query)
		@user_ids = []
		user_belongs.each do |u_b|
			@user_ids.push(u_b.user_id)
		end
  end

	def detail
		@able_users = params[:able_users]
	end

	private
		def	group_params
			params.require(:group).permit(:name, :password, :password_confirmation)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

	def create
		user = User.find_by(name: params[:session][:name]);
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to user
		else
			flash.now[:danger] = "Invalid name/password combination"
			render 'new'
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	include SessionsHelper

	before_action :logged_in_user, only: [:show]

	def show
		@user = User.find(params[:id])
		query = "SELECT group_id FROM belongs WHERE user_id = #{@user.id}"
		@group_ids = Belong.find_by_sql(query)
	end

  def new
		@user = User.new
  end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to Meeting Scheduler"
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end



	private

		def user_params
			params.require(:user).permit(:name, :password, :password_confirmation)
		end

		def correct_user
				@user = User.find(params[:id])
				redirect_to root_path unless current_user?(@user)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base = "Meeting Scheduler"
		if page_title.empty?
			base
		else
			page_title + " | " + base
		end
	end
end

app/helpers/belongs_helper.rb
module BelongsHelper
end

app/helpers/brankdays_helper.rb
module BrankdaysHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		end
	end
	
	def current_user?(user)
		user == current_user
	end
	
	def logged_in?
		return !current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/belongs/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:belong, url: joingroup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.submit "Join", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/brankdays/new.html.erb
<h1>Brankdays#new</h1>
<p>Find me in app/views/brankdays/new.html.erb</p>
	<div class="col-5 ml-3">
	    <%= form_for(:register, url: register_path) do |f| %>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>月</th>
                    <th>火</th>
                    <th>水</th>
                    <th>木</th>
                    <th>金</th>
                    <th>土</th>
                    <th>日</th>
                </tr>
            </thead>
            <tbody>
								<% for time in 1..5 do%>
									<%= render 'layouts/row', time: time, f: f%>
								<%end%>
            </tbody>
        </table>

      <%= f.submit "Register", class: "btn btn-primary" %>
			<% end %>
    </div>

app/views/groups/_block.html.erb
<td>
	<%
	sum = 0
	query = 
	"SELECT COUNT(*) AS check_sum
				FROM brankdays 
				WHERE user_id = ?
					AND day_id = #{week}
					AND time_id = #{time}"
	able_users = []
	@user_ids.each do |user_id|
		if Brankdays.find_by_sql([query, user_id]).first.check_sum == 1
			sum += 1
			able_users.push(user_id)
		end
	end
	%>
	<% if sum == 0 or !@user_ids.include?(current_user.id) %>
		<%= sum %>
	<% else %>
		<%=link_to sum, detail_path(able_users: able_users)  %>
	<% end %>
</td>

app/views/groups/_row.html.erb
<tr>
<% for num in 1..7 do%>
<%= render 'block', week: num, time: time%>
<% end %>
</tr>

app/views/groups/detail.html.erb
<ul>
<% @able_users.each do|id|%>
	<li>
		<%="#{User.find(id).name}" %>
	</li>
<%end %>
</ul>

app/views/groups/new.html.erb
<% provide(:title, 'Make a Group') %>
<h1>Make a Group</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@group, url: makegroup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Create Group", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/groups/show.html.erb
<%= provide(:title, @group.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @group.name %>
      </h1>
    </section>
			<h1>
			Members
			</h1>
			<ul>
			<% @user_ids.each do |user_id| %>
				<% user = User.find(user_id) %>
				<li><%= link_to "#{user.name}", user %></li>
			<%end %>
			</ul>
		</section>
  </aside>
  <div class="col-md-8">
    <h1>My Schedule</h1>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>月</th>
					<th>火</th>
					<th>水</th>
					<th>木</th>
					<th>金</th>
					<th>土</th>
					<th>日</th>
				</tr>
			</thead>
			<tbody>
				<% for time in 1..5 do %>
					<%= render 'row', time: time%>
				<% end %>
			</tbody>
		</table>
  </div>
</div>

app/views/layouts/_block.html.erb
<td><%= f.check_box :"#{week.to_s}_#{time.to_s}" %></td>

app/views/layouts/_block2.html.erb
<td>
	<%
	query = 
	"SELECT COUNT(*) AS check_sum
				FROM brankdays 
				WHERE user_id = #{current_user.id}
					AND day_id = #{week}
					AND time_id = #{time}"
	if Brankdays.find_by_sql(query).first.check_sum == 1
	%>
		o
	<% else %>
		x
	<% end %>
</td>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 	<div class="container">
   	<nav class="bg-light">
    	<ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Home",   root_path %></li>
				<%if logged_in?%>
      		<li><%= link_to "Profile", current_user %></li>
      		<li><%= link_to "Log out", logout_path %></li>
				<%else%>
      		<li><%= link_to "Log in", login_path %></li>
				<%end%>
			</ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_row.html.erb
<tr>
<% for num in 1..7 do%>
<%= render 'layouts/block', week: num, time: time, f: f %>
<% end %>
</tr>

app/views/layouts/_row2.html.erb
<tr>
<% for num in 1..7 do%>
<%= render 'layouts/block2', week: num, time: time%>
<% end %>
</tr>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
		<%= render 'layouts/rails_default'%> 
		<%= render 'layouts/shim'%> 
  </head>

  <body>
		<%= render 'layouts/header' %>
		<div class="container">
    <%= yield %>
		</div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to Meeting Adjuster</h1>
	<% if logged_in? %>
		<%= link_to "Make a Group!", makegroup_path, class: "btn btn-lg btn-primary" %>
		<%= link_to "Join a Group!", joingroup_path, class: "btn btn-lg btn-primary" %>
	<% else %>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
		<section class="center">
			<%= link_to "Register Schedule", register_path, class: "btn btn-lg btn-primary" %>
		</section>
		<section>
			<h1>
				Groups
			</h1>
			<ul>
			<% @group_ids.each do |group_id| %>
				<% group = Group.find(group_id.group_id) %>
				<li><%= link_to "#{group.name}", group %></li>
			<%end %>
			</ul>
		</section>
  </aside>
  <div class="col-md-8">
    <h1>Schedule</h1>
		<%if current_user == @user%>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>月</th>
					<th>火</th>
					<th>水</th>
					<th>木</th>
					<th>金</th>
					<th>土</th>
					<th>日</th>
				</tr>
			</thead>
			<tbody>
				<% for time in 1..5 do %>
					<%= render 'layouts/row2', time: time%>
				<% end %>
			</tbody>
		</table>
		<%else%>
			<div class="center">
			<h2>Private!</h2>
			</div>
		<%end%>
  </div>
</div>